FROM oven/bun:debian

WORKDIR /app

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y git 

ARG PUBLIC_APP_URL
ARG APP_ENV
ARG APP_URL
ARG DATABASE_URL
ARG OPENAI_API_KEY
ARG CLAUDE_API_KEY
ARG GEMINI_API_KEY
ARG OPENROUTER_API_KEY
ARG GROQ_API_KEY
ARG XAI_API_KEY
ARG MISTRAL_API_KEY
ARG GOOGLE_OAUTH_CLIENT_ID
ARG GOOGLE_OAUTH_CLIENT_SECRET
ARG GITHUB_OAUTH_CLIENT_ID
ARG GITHUB_OAUTH_CLIENT_SECRET
ARG JINA_API_KEY
ARG EXA_API_KEY
ARG TAVILY_API_KEY
ARG VERCEL_API_KEY
ARG VERCEL_APP_PROJECT_ID
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG S3_BUCKET
ARG S3_API_URL
ARG S3_PUBLIC_URL
ARG UPSTASH_ENDPOINT
ARG UPSTASH_SECRET
ARG POLAR_ACCESS_KEY
ARG POLAR_BASIC_PLAN_PRICE_ID
ARG POLAR_PRO_PLAN_PRICE_ID
ARG POLAR_500_CREDITS_PRICE_ID
ARG POLAR_WEBHOOK_SECRET


COPY ./package.json ./
COPY ./bun.lock ./

RUN bun install

COPY . .
# COPY ./.env.example ./.env

RUN bun --bun run build

EXPOSE 3000

CMD ["bun", "build/index.js"]